# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: Cloud Computing Build and Deploy

on:
push:
branches: [ main ]

jobs:
tests:
name: Packer Validation

runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v2
- name: Set up JDK 8
uses: actions/setup-java@v2
with:
java-version: '8.0.322'
distribution: temurin
- name: Cache Maven packages
uses: actions/cache@v1
with:
path: ~/.m2
key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
restore-keys: ${{ runner.os }}-m2

- name: Run Tests
run: mvn -B test

- name: Build Maven
run: |
mvn clean package
pwd
mkdir stage && cp target/health-check-api-0.0.1-SNAPSHOT.jar stage
cp stage/*.jar /home/runner/work/webapp/webapp
cd /home/runner/work/webapp/webapp && ls -all
env:
APP_NAME: my-spring-boot-app




- name: Packer build
uses: hashicorp/packer-github-actions@master
with:
command: build
arguments: "-color=false -on-error=abort"
target: ami.pkr.hcl
working_directory: /home/runner/work/webapp/webapp
env:
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
AWS_DEFAULT_REGION: us-east-1

















# name: Build Packer on Merge

# on:
#   push:
#     branches: [main]

# jobs:
#   build-packer:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up JDK 17
#         uses: actions/setup-java@v3
#         with:
#           java-version: "17"
#           distribution: "temurin"
#           cache: maven
#       - name: Build Maven
#         run: |
#           mvn clean package
#           pwd
#           mkdir stage && cp target/health-check-api-0.0.1-SNAPSHOT.jar stage   
#           cp stage/*.jar /home/runner/work/webapp/webapp
#           cd /home/runner/work/webapp/webapp && ls -all
#       - name: Packer build
#         uses: hashicorp/packer-github-actions@master
#         with:
#           command: build
#           arguments: "-color=false -on-error=abort"
#           target: ami.pkr.hcl
#           working_directory: /home/runner/work/webapp/webapp
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_DEFAULT_REGION: us-east-1
#           # aws_profile: ${{ secrets.AWS_PROFILE}}
